local console   = {}
local maf       = require "lib.maf"
local teller    = require "teller"

local skipText    = false
local textDone    = false
local string      = ""
local maxMessage  = 5

local waitForEmptyConsole = false

function console.init()
    console.pos     = maf.vector(20, 460)
    console.message = {}
    console.active  = true
    --console.update  = true
end

function console.add(newText)
    if #newText < 1 then return end

    table.insert(console.message, newText)
    if #console.message > maxMessage then
        table.remove(console.message, 1)
    end
    textDone = true
    --print("--- Console Messages ---")
    --for i, v in ipairs(console.message) do print(i, v) end
end

function console.toggle()
    console.active = not console.active
end

-- Placeholder function for the text animation
function console.renderText()
    -- this function is generated by updateText
end

-- Event to add a new peice of text and process the variables
function console.updateText(s)
    local s     = s or ""
    local len   = 0
    local newString = ""
    
    -- splitting new lines
    local mess = {}
    for str in string.gmatch(s, "([^\n]+),?") do
        table.insert(mess, str)
    end
    s = mess[1]

    -- wierd hack to add an new empty log
    console.add(" ")

    console.renderText = function()
        if s == nil then return end

        if skipText == true then
            len = #s
            newString = s
        else
            len = math.min(len+0.5, #s)
            newString = string.sub(s, 1, math.floor(len))
        end

        if newString == s then
            table.remove(mess, 1)
            if mess[1] then
                --print("Detected a new line!")
                console.add(" ")
                s = mess[1]
                len = 1
            else
                skipText = false
                textDone = true
            end
        else
            textDone = false
        end

        console.change(newString)
        --graphics.print(newString, diaX, diaY, {}, 1)
    end
end

function console.update()
    -- wierd function to update the text scrolling effect, etc.
    console.renderText()
    console.string = table.concat(console.message, "\n")
end

function console.print()
    if console.active ~= true then return end
    graphics.setDrawColor(1,1,1,1)
    graphics.print(console.string, console.pos.x, console.pos.y - #console.message * graphics.fontSize)
end

function console.clear(clearType)
    local clearType = clearType or "full"
    console.renderText = function() end

    if clearType == "full" then
        console.message = {}
        console.string  = ""        
        return
    end

    for i, v in ipairs(console.message) do
        Timer.every(0.05, function() 
        console.message[i] = string.sub(console.message[i], 0, #console.message[i]-1)
        if #console.message[i] == 0 then
            console.message[i] = ""
            return false
        end
        end)
    end
end
  
function console.change(text, id)
    local id = id or #console.message
    console.message[id] = text
end

function console.textDone()
    return textDone
end

function console.skipToEnd()
    skipText = true
end

return console

